name: Release in Releases (Old codebase)

on:
  push:
    tags:
      - "v*-old"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Gradle build
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.OLD_KEYSTORE_BASE64 }}
          alias: ${{ secrets.OLD_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.OLD_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.OLD_KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv ${{steps.sign_apk.outputs.signedReleaseFile}} lactool.apk

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          files: |
            lactool.apk
